### ISSUE TITLE
Compatibility with Magic Items

### ISSUE THREAD

**Issue by DarKDinDoN** [illandril/FoundryVTT-hotbar-uses#14] opened 2020-10-23 21:46 UTC
Hi,

That would be awesome if this module would be also compatible with Magic Items: https://gitlab.com/riccisi/foundryvtt-magic-items

Magic Items allows to add feats and spells to an item.
If the Magic item is equipped, then the attached feat or spell is shown in the appropriate tab.

**Comment by illandril** [comment] 2020-10-25 21:08
Support for the Magic Items module is not currently feasible due to this issue: https://gitlab.com/riccisi/foundryvtt-magic-items/-/issues/45

If this issue is fixed in Magic Items, then I will re-visit this.

**Comment by benbarbour** [comment] 2020-11-13 16:39
It's dealt with. :) The issue is closed anyway, don't know for sure that it helps you close this one!

**Closed** 2020-11-13 23:08 UTC
Labels: blocked, enhancement

**Comment by DarKDinDoN** [comment] 2020-11-14 11:50
@illandril @benbarbour Not sure it's working.
When dragging a magic item spell or a feat to the macro bar, I don't get the remaining uses.

**Comment by illandril** [comment] 2020-11-14 16:02
Do normal items with uses show in the hotbar correctly?
If not, you may not have the Illandril's Hotbar Uses module active.

Please double-check to make sure you are using Magic Items version 2.0.3 (or newer), and Illandril's Hotbar Uses version 2.0.2.

If you are, try clearing your browser's cache and try again (you can find instructions here if you don't know how to do this: https://www.digitaltrends.com/computing/how-to-clear-your-browser-cache/).
If it works at this point, then your browser was just caching an old copy of one of the scripts.

If it still doesn't work, try again in your browser's incognito mode. If it works at this point, you probably have a browser extension that is causing issues - if you can narrow down which browser extension is causing the problem, I can look into working around the compatibility issue.

If it still doesn't work, right-click your macro and click "Edit Macro". Take and share a screenshot (or multiple screenshots) showing...
1. The edit window for the Magic Items spell/feat macro
2. The hotbar showing the Magic Items macro that isn't working as well as a normal item macro that is working
3. The edit window for the Magic Item itself
4. The character sheet showing the Magic Items section containing the macro's feat/spell
5. The list of Active Modules
6. Your browser's Javascript console showing any and all errors (if there are any)
... and also let me know...
1. Your Foundry and DnD5e versions
2. What browser(s) you are seeing this issue in, including the specific version

**Comment by DarKDinDoN** [comment] 2020-11-14 16:38
@illandril not a cache issue actually.
Not working for the GM user.

**Comment by illandril** [comment] 2020-11-14 17:10
As the GM, are you selecting the character's token?
The Magic Items macros (and most other macros) are not actor-specific, so they act on the "active" token. If you don't have a token selected (and don't have an actor assigned to you), or have a token selected that doesn't have an item with the same name, the "available uses" will be zero, so that macro should show faded with a red border.

**Comment by DarKDinDoN** [comment] 2020-11-14 17:22
Yeah, that is what happening, I'm good with that.
Was misleading cause regular items/feats/spells do show their uses for GM
